version: "3.8"

services:
  service:
    image: service
    restart: always
    env_file:
      - .env
    build: .
    deploy:
      replicas: 2

  nginx-service:
    container_name: nginx-service
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./infra/configs/nginx-service/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/configs/nginx-service/site.conf:/etc/nginx/conf.d/site.conf:ro
    # ports:
    #   - "80:80"
