version: "3.8"

services:
  nginx-gateway:
    container_name: nginx-gateway
    image: nginx:1.25.5
    restart: always
    volumes:
      - ${INFRA_CONFIG}/nginx-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${INFRA_CONFIG}/nginx-gateway/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"

networks:
  default:
    driver: bridge
    external: true
    name: project-network
